Tp sl update
bybit-exchange/docs-legacy pull request #100
Opened 2020-08-27 06:46 UTC by EricZ11

take profit stop loss version update

2020-09-24 11:54 UTC, dexter-2 commented on locales/en.yml
> +    <p>Return value ext_code is not empty,Please refer to <a href="#t-errors">Errors</a></p>
Can you clarify what this means? I don't understand.

2020-09-24 12:26 UTC, dexter-2 commented on locales/en.yml
> +  err_130156: Modify the trigger price when the price and quantity of the active order is not allowed.
Please clarify this error? I don't understand it.

2020-09-24 12:27 UTC, dexter-2 commented on locales/en.yml
> +  err_130159: There are more than 20 SL/TP settings in the partial SL/TP mode.
Please also clarify `err_130158` `err_130159`

2020-09-24 12:36 UTC, dexter-2 commented on locales/en.yml
> -  account_para_tradingStop: Set take profit, stop loss, and trailing stop for your open position.
Need two versions of this for inverse & linear:
- inverse: `account_para_tradingStop`: Set take profit, stop loss, and trailing stop for your open position.
- linear: `account_para_tradingStop_linear`: The new version added in this PR.

**So please add `account_para_tradingStop_linear` to zh-cn.yml**

2020-09-24 13:37 UTC, dexter-2 commented
I have a local review ready to push, just waiting on responses to my above comments so that I may make minor adjustments.

2020-09-25 04:06 UTC, EricZ11 reviewed
err_130153: Switching failed. There is profit stop loss setting
err_130154: Switching failed. active orders have TP/SL setting.
err_130155: Insufficient quantity
err_130156: replace active order price at the same time replace qty is not allowed

2020-09-25 08:38 UTC, dexter-2 requested changes
Review PR: #107

2020-09-28 06:47 UTC, merged