add wallet endpoint translation
bybit-exchange/docs-legacy pull request #11
Opened 2020-02-05 06:04 UTC by keyganker

2020-02-05 06:05 UTC, keyganker commented on locales/en.yml
> +  wallet_aside_tradeRecords: One order may has multiple trade records.
One order may also has multiple trade records

2020-02-05 06:06 UTC, keyganker commented on locales/en.yml
> +  wallet_aside_tradeRecords: One order may has multiple trade records.
@dexter-2

2020-02-05 06:06 UTC, keyganker commented
@dexter-2

2020-02-05 06:29 UTC, keyganker commented on locales/en.yml
> +    <p>For current endpoint, one withdrawal operation one record, and you can check current withdrawal state by field <code>status</code>.</p>
Add note for wallet fund record endpoint and withdraw record endpoint

2020-02-05 06:30 UTC, keyganker commented on locales/en.yml
> +    <p>For <code>Wallet Fund Records</code> endpoint，once user submited the withdrawal application, there will be a record whith type <code>Withdraw</code>, and if the application is <code>CancelByUs
Add note for wallet fund record endpoint and withdraw record endpoint

2020-02-05 14:42 UTC, dexter-2 commented on source/includes/inverse_future/_wallet_data.md
> +        "order_id": "t(:comment_abandoned)", // t(:comment_abandoned)
What does this mean?

2020-02-05 15:24 UTC, dextertd requested changes
#13

2020-02-05 15:25 UTC, dexter-2 commented on locales/en.yml
> +    <p>For <code>Wallet Fund Records</code> endpoint，once user submited the withdrawal application, there will be a record whith type <code>Withdraw</code>, and if the application is <code>CancelByUs
I'm 100% sure I understand this... But I have tried to make it more clear in my review PR.

2020-02-06 08:01 UTC, keyganker commented on source/includes/inverse_future/_wallet_data.md
> +        "order_id": "t(:comment_abandoned)", // t(:comment_abandoned)
there is a historical reason:
Initially, this endpoint only support query by order_id, and so the response is :
```
{
order_id:xxx,
list:[
  trade item1
  trade item 2
]
}
```
and later it support query without order_id, so the order_id in the response is moved into the list:
```
{
order_id:"",//abandoned
list:[
  trade item1 with order_id1
  trade item 2 with order_id2
]
}

```

2020-02-06 08:02 UTC, keyganker commented on source/includes/inverse_future/_wallet_data.md
> +        "order_id": "t(:comment_abandoned)", // t(:comment_abandoned)
> What does this mean?

there is a historical reason:
Initially, this endpoint only support query by order_id, and so the response is :
```
{
order_id:xxx,
list:[
  trade item1
  trade item 2
]
}
```
and later it support query without order_id, so the order_id in the response is moved into the list:
```
{
order_id:"",//abandoned
list:[
  trade item1 with order_id1
  trade item 2 with order_id2
]
}

```

2020-02-06 08:02 UTC, merged