废弃与新增接口
bybit-exchange/docs-legacy pull request #120
Opened 2020-11-06 10:09 UTC by EricZ11

2020-11-06 10:16 UTC, dexter-2 commented
New Set Leverage endpoint is the same as the abandoned one? `/user/leverage/save`

2020-11-06 10:20 UTC, dexter-2 commented on locales/en.yml
> +  row_comment_cursor: Page turning mark，Use return <code>cursor</code>
How does this work? I don't understand.

2020-11-09 02:57 UTC, EricZ11 commented on locales/en.yml
> +  row_comment_cursor: Page turning mark，Use return <code>cursor</code>
it's similar `/v2/private/exchange-order/list`  ->  from

2020-11-09 09:03 UTC, dexter-2 commented on locales/en.yml
> +  row_comment_cursor: Page turning mark，Use return <code>cursor</code>
I still don't really understand... Could you provide sample data that would be sent as the value of `cursor`?

2020-11-09 10:10 UTC, dexter-2 requested changes
Review PR #121

2020-11-10 03:38 UTC, EricZ11 commented on locales/en.yml
> +  row_comment_cursor: Page turning mark，Use return <code>cursor</code>
urlencode after: GMts5r8FUBO2QWB3gqsbjqD%2BEM0dSlVjbxtxDTs%2Bns3x29g%2BTvMtbRAa

2020-11-10 13:03 UTC, merged