Add kline
bybit-exchange/docs-legacy pull request #152
Opened 2021-01-06 11:51 UTC by BoWang2

added index price kLine and premium indices kLine

2021-01-07 21:35 UTC, dexter-2 commented
Why is it `/v2/public/premium-indices-kline` instead of `/v2/public/premium-index-kline`? It is not plural on the website 
![image](https://user-images.githubusercontent.com/54495183/103947583-35edf780-5130-11eb-8ca1-4be508ac2fcc.png)

2021-01-11 03:15 UTC, BoWang2 commented
> Why is it `/v2/public/premium-indices-kline` instead of `/v2/public/premium-index-kline`? It is not plural on the website
> ![image](https://user-images.githubusercontent.com/54495183/103947583-35edf780-5130-11eb-8ca1-4be508ac2fcc.png)

has changed it into /v2/public/premium-index-kline

2021-01-11 10:19 UTC, dexter-2 commented on source/includes/inverse_future/_market_data.md
> +            "period":"1",
Also I am surprised this is `period` instead of `interval`? Seems like an inconsistency which could confuse the user

2021-01-11 10:37 UTC, dexter-2 requested changes
Thanks for changing the route names!

Review PR: #154

2021-01-12 06:37 UTC, merged

2021-01-12 19:42 UTC, dexter-2 commented
> Also I am surprised this is `period` instead of `interval`? Seems like an inconsistency which could confuse the user

Was this comment considered? Please reply, an inconsistent API is an incredibly important issue in the eyes of devs using the API.