update changelog
bybit-exchange/docs-legacy pull request #221
Opened 2021-06-17 11:00 UTC by BoWang2

2021-06-17 11:01 UTC, BoWang2 commented
@dextertd please review this pull request. Thank you

2021-06-17 15:31 UTC, dextertd commented
@BoWang2 Is it better for users to always use `/v2/private/position/switch-isolated` rather than `/v2/private/position/leverage/save`? They seem to fulfil the same purpose and have the same parameters.

2021-06-17 15:34 UTC, dextertd requested changes

2021-06-17 15:34 UTC, dextertd commented on locales/en.yml
> +  account_aside_setleverage: This endpoint only concerns isolated margin. If you want to use cross margin, please use the <a href="Cross/Isolated Margin Switch"></a> endpoint.
@BoWang2 Please translate the equivalent `account_aside_setleverage` in `zh-cn.yml`

2021-06-17 15:35 UTC, dextertd commented on locales/en.yml
> +  account_aside_setleverage: This endpoint only concerns isolated margin. If you want to use cross margin, please use the <a href="Cross/Isolated Margin Switch"></a> endpoint.
Once that is done we can merge

2021-06-18 03:02 UTC, BoWang2 commented on locales/en.yml
> +  account_aside_setleverage: This endpoint only concerns isolated margin. If you want to use cross margin, please use the <a href="Cross/Isolated Margin Switch"></a> endpoint.
have Done

2021-06-18 03:41 UTC, EricZ11 commented
> @BoWang2用户总是使用`/v2/private/position/switch-isolated`而不是更好`/v2/private/position/leverage/save`吗？它们似乎实现相同的目的并具有相同的参数。

/v2/private/position/leverage/save will update please review.

2021-06-18 08:54 UTC, dextertd approved these changes

2021-06-18 08:55 UTC, merged