Stop order endpoints
bybit-exchange/docs-legacy pull request #34
Opened 2020-04-08 11:43 UTC by keyganker

2020-04-08 15:32 UTC, keyganker commented
@dexter-2 we'll release it on 4.9

2020-04-08 20:56 UTC, dextertd requested changes
#35

2020-04-08 20:56 UTC, dexter-2 commented on locales/en.yml
> +  bugfix_20200410: Change market api curl example URL
This doesn't need to be displayed in the changelog with `t(:bugfix_20200410)` as users don't need to know about changes to the docs.

2020-04-08 20:56 UTC, dexter-2 commented on locales/en.yml
> +  bugfix1_20200409: refine chinese doc
Same here (see above comment)

2020-04-08 20:56 UTC, dexter-2 commented on source/includes/linear_future/_account_data.md
> +|reduce_only |true |bool |t(:linear_row_comment_reduceOnly) |
Should this be `true`? I notice `reduce_only` and `close_on_trigger` are also set for true in linear Place Active Order. I'm not sure if this is correct?

2020-04-09 07:55 UTC, keyganker commented on source/includes/linear_future/_account_data.md
> +|reduce_only |true |bool |t(:linear_row_comment_reduceOnly) |
Will mark `close_on_trigger ` as required  to be consistent with ` linear Place Active Order`.
Thanks!

2020-04-09 07:57 UTC, merged