Update en.yml
bybit-exchange/docs-legacy pull request #346
Opened 2021-12-09 13:20 UTC by lucilae

Added push frequency for futures websockets.

2021-12-09 13:21 UTC, dextertd requested changes
@petifish Please help review Chinese doc, thanks

2021-12-10 03:12 UTC, petifish approved these changes

2021-12-10 03:13 UTC, petifish approved these changes

2021-12-10 03:14 UTC, petifish approved these changes

2021-12-10 03:18 UTC, Kamsby approved these changes

2021-12-10 03:19 UTC, blacksabbather approved these changes

2021-12-10 03:19 UTC, blacksabbather approved these changes

2021-12-10 03:46 UTC, petifish approved these changes

2021-12-10 03:48 UTC, petifish approved these changes

2021-12-10 03:50 UTC, petifish requested changes
done

2021-12-10 03:51 UTC, petifish approved these changes

2021-12-10 03:52 UTC, petifish commented
> @petifish Please help review Chinese doc, thanks

done

2021-12-10 08:10 UTC, dextertd approved these changes

2021-12-10 10:30 UTC, merged