Add Account/Trading inverse response
bybit-exchange/docs-legacy pull request #69
Opened 2020-06-09 10:51 UTC by StrawberryOu

2020-06-17 12:47 UTC, dexter-2 commented on .vscode/launch.json
> +{
Please add this file to your `.gitignore`!

2020-06-18 20:03 UTC, dexter-2 commented on locales/en.yml
> +  marketaccountratio: Account Long-Empty Ratio
Should this be "Account Long-Short Ratio"?

2020-06-18 21:00 UTC, dexter-2 commented
Given the addition of Response Parameters tables we could consider removing the // comments from Response Example codeblocks (and change from 
![image](https://user-images.githubusercontent.com/54495183/85071051-ceca1f00-b1ae-11ea-9d69-4d51c316c731.png) to 
![image](https://user-images.githubusercontent.com/54495183/85071132-eef9de00-b1ae-11ea-87b3-a76d563840ed.png)?

At the moment cannot use json as it errors out the comments.

2020-06-18 21:49 UTC, dextertd requested changes
I added the following entry to en.yml, please add corresponding entry to zh-cn.yml
- `row_comment_exec_type`

Review PR: #72

2020-06-18 21:54 UTC, dexter-2 commented on locales/en.yml
> +  marketbigdeal: Actively Clinched Large Orders
"Actively Clinched"? Not sure what this means, can we change it to something else?

2020-06-27 08:32 UTC, awohan commented
fill response

2020-06-27 08:33 UTC, merged